version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
python:
  version: "3.8"
  install:
    - requirements: requirements-project.txt
    - requirements: requirements-dev.txt
    - requirements: requirements.txt
