version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
python:
  version: 3.8
  install:
  - method: pip
  - path: build
  - requirements: requirements-project.txt
  - requirements: requirements-dev.txt
  - requirements: requirements.txt
