# Python images provided by https://hub.docker.com/_/python

version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  build-python-oldest:
    docker:
      - image: python:3.6.15-bullseye

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Indicate build profile
          command: |
            GIT_WORKING_BRANCH="$(git branch | grep \* | cut -d ' ' -f2)"
            if [ $GIT_WORKING_BRANCH = "main" ]
            then
                BRANCH_STAGE=${BRANCH_STAGE:="master"}
            else
                BRANCH_STAGE=${BRANCH_STAGE:="develop"}
            fi
            echo "Source edition matches '${BRANCH_STAGE}' (branch '${GIT_WORKING_BRANCH}')"

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            chmod +x ./*.sh
            ./init-webdrivers.sh

      - run:
          name: Install Python dependencies
          command: |
            pip install --no-cache-dir -U -r ./requirements-project.txt
            invoke init --dev --list

      - run:
          name: Static analysis
          command: |
            prospector \
                --zero-exit \
                --show-profile \
                --no-autodetect \
                --strictness low \
                -o text \
                ./canvasxpress

      - run:
          name: Test and report
          command: |
            invoke test
            invoke report

      - run:
          name: Deploy artifacts
          command: ./distribute_package.sh

workflows:
  main:
    jobs:
      - build-python-oldest
