version: 2.1

orbs:
    python: circleci/python@0.2.1
    browser-tools: circleci/browser-tools@1.1.3

jobs:
    build-test-release:
        executor: python/default
        steps:
            # Acquire source
            - checkout

            # Python config
            - python/load-cache
            - python/install-deps
            - python/save-cache

            # Browser installations
            - browser-tools/install-firefox
            - browser-tools/install-geckodriver
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                command: |
                    google-chrome --version
                    chromedriver --version
                name: Check install

            # Project build, test, and release
            - run:
                command: chmod +x ./build.sh
                name: prep-build-script
            - run:
                command: ./build.sh
                name: build

workflows:
    main:
        jobs:
            - build-test-release
