# Python images provided by https://hub.docker.com/_/python

version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  build-python-oldest:
    docker:
      - image: python:3.6.15-bullseye

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Indicate build profile
          command: |
            echo "User: $(whoami) | User ID: ${UID} | Group ID: ${GID}"

            GIT_WORKING_BRANCH="$(git branch | grep \* | cut -d ' ' -f2)"
            if [ $GIT_WORKING_BRANCH = "main" ]
            then
                BRANCH_STAGE=${BRANCH_STAGE:="master"}
            else
                BRANCH_STAGE=${BRANCH_STAGE:="develop"}
            fi
            echo "Source edition matches '${BRANCH_STAGE}' (branch '${GIT_WORKING_BRANCH}')"

      - run:
          name: Install Web drivers
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBIAN_PRIORITY=critical
            apt-get update -y
            apt-get install -yq apt-utils

            # Install the FireFox browser
            apt-get -yq update; apt-get -yq install --fix-missing xvfb
            apt-get -yq update; apt-get -yq install --fix-missing x11-utils
            apt-get -yq update; apt-get -yq install --fix-missing firefox-esr
            which firefox
            firefox --version

            # Install the FireFox webdriver
            export FIREFOX_EDITION="v0.29.1"
            wget https://github.com/mozilla/geckodriver/releases/download/${FIREFOX_EDITION}/geckodriver-${FIREFOX_EDITION}-linux64.tar.gz
            tar xvfz geckodriver-${FIREFOX_EDITION}-linux64.tar.gz
            chmod +x geckodriver
            mv geckodriver /usr/local/bin/
            which geckodriver
            geckodriver --version

            # Install the Chromium browser
            apt-get install -yq chromium
            which chromium
            chromium --version

            # Install the Chromium webdriver
            apt-get -yq update
            apt-get -yq install --fix-missing chromium-driver
            which chromedriver
            chromedriver --version

      - run:
          name: Install Python dependencies
          command: |
            pip install --no-cache-dir -U -r ./requirements-project.txt
            invoke init --dev --list

      - run:
          name: Static analysis
          command: |
            prospector \
                --zero-exit \
                --show-profile \
                --no-autodetect \
                --strictness low \
                -o text \
                ./canvasxpress

      - run:
          name: Test and report
          command: |
            invoke test
            invoke report

      - run:
          name: Deploy artifacts
          command: ./distribute_package.sh

workflows:
  main:
    jobs:
      - build-python-oldest
