# Python images provided by https://hub.docker.com/_/python

version: 2.1

jobs:
  build-python-general:
    docker:
      - image: python:3.10.12-bullseye

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Indicate build profile
          command: |
            echo "User: $(whoami) | User ID: ${UID} | Group ID: ${GID}"

            GIT_WORKING_BRANCH="$(git branch | grep \* | cut -d ' ' -f2)"
            if [ $GIT_WORKING_BRANCH = "main" ]
            then
                BRANCH_STAGE=${BRANCH_STAGE:="master"}
            else
                BRANCH_STAGE=${BRANCH_STAGE:="develop"}
            fi
            echo "Source edition matches '${BRANCH_STAGE}' (branch '${GIT_WORKING_BRANCH}')"

      - run:
          name: Install Linux Packages
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBIAN_PRIORITY=critical

            apt-get -yq update
            apt-get -yq upgrade

            # Package installation support
            apt-get install -yq --fix-missing debconf-utils
            apt-get install -yq --fix-missing dialog
            apt-get install -yq --fix-missing apt-utils

            # File acquisition support
            apt-get install -yq --fix-missing wget
            apt-get install -yq --fix-missing curl

            # Fundamental software build support
            apt-get install -yq --fix-missing gcc
            apt-get install -yq --fix-missing make
            apt-get install -yq --fix-missing cmake
            apt-get install -yq --fix-missing build-essential

            # R for RStudio support
            apt-get install -yq --fix-missing r-base
            apt-get install -yq --fix-missing r-base-dev

      - run:
          name: Install Web drivers
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBIAN_PRIORITY=critical
            apt-get update -y
            apt-get install -yq apt-utils

            # Install the Chromium browser
            apt-get install -yq chromium
            which chromium
            chromium --version

            # Install the Chromium webdriver
            apt-get -yq update
            apt-get -yq install --fix-missing chromium-driver
            which chromedriver
            chromedriver --version

      - run:
          name: Install Node and NPM for Dash and General Python
          command: |
            apt-get -yq install --fix-missing nodejs
            apt-get -yq install --fix-missing npm
            node --version
            npm --version

      - run:
          name: Install Python dependencies
          command: |
            pip install --no-cache-dir -U -r ./requirements-project.txt
            invoke init --dev --list

      - run:
          name: Generate Dash Component
          command: |
            cd plotly/cxdash/

            #  Ensure the presence of a virtual environment
            if ! [[ -d ./venv ]] ; then
                python3 -m venv ./venv
            fi
            source ./venv/bin/activate

            # Ensure that essential project utilities are available
            pip install -U pip setuptools wheel
            pip install -U -r requirements.txt

            npm install canvasxpress
            npm install canvasxpress-react

            npm run build
            cp -R ./cxdash ../../

      - run:
          name: Install Node and NPM for Streamlit
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x -o setup_nodejs.sh
            sh ./setup_nodejs.sh
            apt update
            apt install -yq --fix-missing nodejs
            node --version
            npm --version
            npm cache clear --force

      - run:
          name: Generate Streamlit Component
          command: |
            cd streamlit/

            #  Ensure the presence of a virtual environment
            if ! [[ -d ./venv ]] ; then
                python3 -m venv ./venv
            fi
            source ./venv/bin/activate
            pip install -r ./requirements.txt

            # Build the React component
            # shellcheck disable=SC2164
            cd ./cxstreamlit/frontend/
            echo "Installling JS packages..."
            npm install
            ls -lah
            echo "Building JS package..."
            npm run build
            ls -lah
            cd ../../../

            # Copy the Python package
            mkdir -p cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/frontend/build cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/frontend/*.json cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/frontend/*.js cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/*.py cxstreamlit/

            # Add package markers for build inclusion
            touch cxstreamlit/frontend/__init__.py
            touch cxstreamlit/frontend/build/__init__.py
            touch cxstreamlit/frontend/build/static/__init__.py
            touch cxstreamlit/frontend/build/static/css/__init__.py
            touch cxstreamlit/frontend/build/static/js/__init__.py

            ls -lah cxstreamlit
            ls -lah cxstreamlit/frontend/
            ls -lah cxstreamlit/frontend/build/
            ls -lah cxstreamlit/frontend/build/static/
            ls -lah cxstreamlit/frontend/build/static/js/
            ls -lah cxstreamlit/frontend/build/static/css/

      - run:
          name: Static analysis
          command: |
            prospector \
                --zero-exit \
                --show-profile \
                --no-autodetect \
                --strictness low \
                -o text \
                ./canvasxpress

      - run:
          name: Test
          command: invoke test

      - store_test_results:
          path: pytest_result.xml

      - run:
          name: Report
          command: invoke report

      - run:
          name: Deploy artifacts
          command: |
            echo "Repository is from $(git config --get remote.origin.url)"
            GIT_REPO_OWNER="$(git config --get remote.origin.url | cut -d: -f2 | cut -d/ -f1)"
            echo "Found repository owner ${GIT_REPO_OWNER}"

            # Only attempt the deployment for the project owner/committer
            if [ $GIT_REPO_OWNER == "docinfosci" ]
            then
              # Establish package components
              rm -rf ./dist
              python ./build_pkg_setup.py
              python setup.py sdist

              # Confirm the installation user account
              echo "Deploying via TWINE user ${TWINE_USERNAME}"

              # Only publish non-dev editions to PyPI
              GIT_WORKING_BRANCH="$(git branch | grep \* | cut -d ' ' -f2)"
              if [ $GIT_WORKING_BRANCH == "main" ]
              then
                  # Production deployment
                  twine upload --verbose -u $TWINE_USERNAME -p $PRD_TWINE_PASSWORD --repository pypi ./dist/*

              else
                  # Development deployment
                  twine upload --verbose -u $TWINE_USERNAME -p $TWINE_PASSWORD --repository testpypi ./dist/*

              fi

            else
              echo "Skipping deployment for repository owner ${GIT_REPO_OWNER}"

            fi

  build-python-latest:
    docker:
      - image: python:3.11.4-bullseye

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Indicate build profile
          command: |
            echo "User: $(whoami) | User ID: ${UID} | Group ID: ${GID}"

            GIT_WORKING_BRANCH="$(git branch | grep \* | cut -d ' ' -f2)"
            if [ $GIT_WORKING_BRANCH = "main" ]
            then
                BRANCH_STAGE=${BRANCH_STAGE:="master"}
            else
                BRANCH_STAGE=${BRANCH_STAGE:="develop"}
            fi
            echo "Source edition matches '${BRANCH_STAGE}' (branch '${GIT_WORKING_BRANCH}')"

      - run:
          name: Install Linux Packages
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBIAN_PRIORITY=critical

            apt-get -yq update
            apt-get -yq upgrade

            # Package installation support
            apt-get install -yq --fix-missing debconf-utils
            apt-get install -yq --fix-missing dialog
            apt-get install -yq --fix-missing apt-utils

            # File acquisition support
            apt-get install -yq --fix-missing wget
            apt-get install -yq --fix-missing curl

            # Fundamental software build support
            apt-get install -yq --fix-missing gcc
            apt-get install -yq --fix-missing make
            apt-get install -yq --fix-missing cmake
            apt-get install -yq --fix-missing build-essential

            # R for RStudio support
            apt-get install -yq --fix-missing r-base
            apt-get install -yq --fix-missing r-base-dev

      - run:
          name: Install Web drivers
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBIAN_PRIORITY=critical
            apt-get update -y
            apt-get install -yq apt-utils

            # Install the Chromium browser
            apt-get install -yq chromium
            which chromium
            chromium --version

            # Install the Chromium webdriver
            apt-get -yq update
            apt-get -yq install --fix-missing chromium-driver
            which chromedriver
            chromedriver --version

      - run:
          name: Install Node and NPM for Dash and General Python
          command: |
            apt-get -yq install --fix-missing nodejs
            apt-get -yq install --fix-missing npm
            node --version
            npm --version

      - run:
          name: Install Python dependencies
          command: |
            pip install --no-cache-dir -U -r ./requirements-project.txt
            invoke init --dev --list

      - run:
          name: Generate Dash Component
          command: |
            cd plotly/cxdash/

            #  Ensure the presence of a virtual environment
            if ! [[ -d ./venv ]] ; then
                python3 -m venv ./venv
            fi
            source ./venv/bin/activate

            # Ensure that essential project utilities are available
            pip install -U pip setuptools wheel
            pip install -U -r requirements.txt

            npm install canvasxpress
            npm install canvasxpress-react

            npm run build
            cp -R ./cxdash ../../

      - run:
          name: Install Node and NPM for Streamlit
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x -o setup_nodejs.sh
            sh ./setup_nodejs.sh
            apt update
            apt install -yq --fix-missing nodejs
            node --version
            npm --version
            npm cache clear --force

      - run:
          name: Generate Streamlit Component
          command: |
            cd streamlit/

            #  Ensure the presence of a virtual environment
            if ! [[ -d ./venv ]] ; then
                python3 -m venv ./venv
            fi
            source ./venv/bin/activate
            pip install -r ./requirements.txt

            # Build the React component
            # shellcheck disable=SC2164
            cd ./cxstreamlit/frontend/
            echo "Installling JS packages..."
            npm install
            ls -lah
            echo "Building JS package..."
            npm run build
            ls -lah
            cd ../../../

            # Copy the Python package
            mkdir -p cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/frontend/build cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/frontend/*.json cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/frontend/*.js cxstreamlit/frontend/
            cp -R streamlit/cxstreamlit/*.py cxstreamlit/

            # Add package markers for build inclusion
            touch cxstreamlit/frontend/__init__.py
            touch cxstreamlit/frontend/build/__init__.py
            touch cxstreamlit/frontend/build/static/__init__.py
            touch cxstreamlit/frontend/build/static/css/__init__.py
            touch cxstreamlit/frontend/build/static/js/__init__.py

            ls -lah cxstreamlit
            ls -lah cxstreamlit/frontend/
            ls -lah cxstreamlit/frontend/build/
            ls -lah cxstreamlit/frontend/build/static/
            ls -lah cxstreamlit/frontend/build/static/js/
            ls -lah cxstreamlit/frontend/build/static/css/

      - run:
          name: Test
          command: invoke test

      - store_test_results:
          path: pytest_result.xml

  build-python-oldest:
    docker:
      - image: python:3.8.18-bullseye

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Indicate build profile
          command: |
            echo "User: $(whoami) | User ID: ${UID} | Group ID: ${GID}"

            GIT_WORKING_BRANCH="$(git branch | grep \* | cut -d ' ' -f2)"
            if [ $GIT_WORKING_BRANCH = "main" ]
            then
                BRANCH_STAGE=${BRANCH_STAGE:="master"}
            else
                BRANCH_STAGE=${BRANCH_STAGE:="develop"}
            fi
            echo "Source edition matches '${BRANCH_STAGE}' (branch '${GIT_WORKING_BRANCH}')"

      - run:
          name: Install Linux Packages
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBIAN_PRIORITY=critical

            apt-get -yq update
            apt-get -yq upgrade

            # Package installation support
            apt-get install -yq --fix-missing debconf-utils
            apt-get install -yq --fix-missing dialog
            apt-get install -yq --fix-missing apt-utils

            # File acquisition support
            apt-get install -yq --fix-missing wget
            apt-get install -yq --fix-missing curl

            # Fundamental software build support
            apt-get install -yq --fix-missing gcc
            apt-get install -yq --fix-missing make
            apt-get install -yq --fix-missing cmake
            apt-get install -yq --fix-missing build-essential

            # R for RStudio support
            apt-get install -yq --fix-missing r-base
            apt-get install -yq --fix-missing r-base-dev

      - run:
          name: Install Web drivers
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBIAN_PRIORITY=critical
            apt-get update -y
            apt-get install -yq apt-utils

            # Install the Chromium browser
            apt-get install -yq chromium
            which chromium
            chromium --version

            # Install the Chromium webdriver
            apt-get -yq update
            apt-get -yq install --fix-missing chromium-driver
            which chromedriver
            chromedriver --version

      - run:
          name: Install Node and NPM for Dash and General Python
          command: |
            # Configure Node 22 repository config
            cd /tmp
            curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
            chmod +x ./nodesource_setup.sh
            ./nodesource_setup.sh

            # Install Node
            apt-get clean
            apt-get autoclean
            apt-get autoremove

            apt-get install -yqf nodejs

            node --version
            npm --version

      - run:
          name: Install Python dependencies
          command: |
            pip install --no-cache-dir -U -r ./requirements-project.txt
            invoke init --dev --list

      - run:
          name: Generate Dash Component
          command: |
            cd plotly/cxdash/

            #  Ensure the presence of a virtual environment
            if ! [[ -d ./venv ]] ; then
                python3 -m venv ./venv
            fi
            source ./venv/bin/activate

            # Ensure that essential project utilities are available
            echo "Install Python components"
            pip install -U pip setuptools wheel
            pip install -U -r requirements.txt

            echo "Install CanvasXpress NodeJS components"
            npm install canvasxpress
            npm install canvasxpress-react

            echo "Update NodeJS components"
            npm audit fix --force

            echo "Run build"
            npm run build
            cp -R ./cxdash ../../

      - run:
          name: Install Node and NPM for Streamlit
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x -o setup_nodejs.sh
            sh ./setup_nodejs.sh
            apt update
            apt install -yq --fix-missing nodejs
            node --version
            npm --version
            npm cache clear --force

      - run:
          name: Generate Streamlit Component
          command: |
            echo "Streamlit requires Python 3.7 and later due to PyArrow."
            #            cd streamlit/
            #
            #            #  Ensure the presence of a virtual environment
            #            if ! [[ -d ./venv ]] ; then
            #                python3 -m venv ./venv
            #            fi
            #            source ./venv/bin/activate
            #            pip install -r ./requirements.txt
            #
            #            # Build the React component
            #            # shellcheck disable=SC2164
            #            cd ./cxstreamlit/frontend/
            #            echo "Installling JS packages..."
            #            npm install
            #            ls -lah
            #            echo "Building JS package..."
            #            npm run build
            #            ls -lah
            #            cd ../../../
            #
            #            # Copy the Python package
            #            mkdir -p cxstreamlit/frontend/
            #            cp -R streamlit/cxstreamlit/frontend/build cxstreamlit/frontend/
            #            cp -R streamlit/cxstreamlit/frontend/*.json cxstreamlit/frontend/
            #            cp -R streamlit/cxstreamlit/frontend/*.js cxstreamlit/frontend/
            #            cp -R streamlit/cxstreamlit/*.py cxstreamlit/
            #
            #            # Add package markers for build inclusion
            #            touch cxstreamlit/frontend/__init__.py
            #            touch cxstreamlit/frontend/build/__init__.py
            #            touch cxstreamlit/frontend/build/static/__init__.py
            #            touch cxstreamlit/frontend/build/static/css/__init__.py
            #            touch cxstreamlit/frontend/build/static/js/__init__.py
            #
            #            ls -lah cxstreamlit
            #            ls -lah cxstreamlit/frontend/
            #            ls -lah cxstreamlit/frontend/build/
            #            ls -lah cxstreamlit/frontend/build/static/
            #            ls -lah cxstreamlit/frontend/build/static/js/
            #            ls -lah cxstreamlit/frontend/build/static/css/

      - run:
          name: Test
          command: invoke test

      - store_test_results:
          path: pytest_result.xml

workflows:
  github-commit:
    jobs:
      - build-python-oldest
      - build-python-latest
      - build-python-general:
          requires:
            - build-python-oldest
            - build-python-latest

  weekly:
    jobs:
      - build-python-oldest
      - build-python-latest
      - build-python-general:
          requires:
            - build-python-oldest
            - build-python-latest

    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - main