version: 2.1

orbs:
    python: circleci/python@0.2.1

jobs:
    build-and-test:
        executor: python/default
        steps:
            - checkout
            - python/load-cache
            - python/install-deps
            - python/save-cache
            -   run:
                    command: chmod +x ./build.sh
                    name: prep-build-script
            -   run:
                    command: ./build.sh
                    name: build

workflows:
    main:
        jobs:
            - build-and-test
