
name = "Cxdash"
uuid = "1b08a953-4be3-4667-9a23-9619cadea094"
authors = ["Original JS library and React by Isaac Neuhaus; Python and Dash JS by Todd Brett. <todd@aggregate-genius.com>"]
version = "1.1.0"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
